### ISSUE TITLE
store answers in session and add question number in url

### ISSUE THREAD

**Issue by alcalyn** [cgrandval/ZCEPracticeTest#12]
If the user refreshes, all data must be persisted.

**Comment by alcalyn** [comment]
Will be done:
- Persist in $localStorage user answers,
- Use urls like "#/quiz/question/69" (will keep the quiz position when refreshing),
- Persist in $localStorage quiz position (and use it at page load if position isn't in url).

**Comment by alcalyn** [comment]
Urls are not changed, no need, position is stored/retrieved as well

**Comment by cgrandval** [comment]
Directly after finishing a test, if I return on the panel, the current session box is displayed. But if I refresh the page, the current box disappears and the finish box appears.
