### ISSUE TITLE
When passing a test, the last 2 "clicked" on radio buttons seem to be saved

### ISSUE THREAD

**Issue by cgrandval** [cgrandval/ZCEPracticeTest#26]
When passing a test, if you choose an answer (click on the radio button), then click on another to change your choice, it seems that the app saves the 2 last "clicked".

![capture d ecran 2015-01-23 a 20 27 02](https://cloud.githubusercontent.com/assets/903317/5884574/3b9d3c5a-a33e-11e4-8700-d30831bba2e9.png)

**Comment by alcalyn** [comment]
That was expected.

The yellow check is here to say to user that he don't have checked this answer whereas it is a good answer.

This is an ergonomy bug, the yellow check should be removed, or be replaced by another thing...

**Comment by alcalyn** [comment]
But there is no bug when user change his answer

**Comment by cgrandval** [comment]
Ok :-), I think you can remove the yellow check. The user can see what answer was expected.
